// This file is @generated by prost-build.
/// Manifest sent on /graph/init. Tiny — just metadata for setup.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Init {
    #[prost(uint32, tag = "1")]
    pub n_nodes: u32,
    #[prost(uint32, tag = "2")]
    pub n_edges: u32,
    #[prost(uint32, tag = "3")]
    pub num_communities: u32,
    #[prost(uint32, tag = "4")]
    pub num_wcc: u32,
    /// Color palette as flat r,g,b,r,g,b,... (3 floats per color).
    /// Future: clients pass color preferences; server returns derived palette.
    #[prost(float, repeated, tag = "5")]
    pub palette: ::prost::alloc::vec::Vec<f32>,
}
/// Per-node metadata. Returned by /node/:id (sparse, on-demand).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeMeta {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub folder: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub doctype: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Frontmatter as JSON-encoded string. Keeping this opaque avoids re-encoding
    /// arbitrary YAML in protobuf — frontends parse JSON.
    #[prost(string, tag = "7")]
    pub frontmatter_json: ::prost::alloc::string::String,
    #[prost(uint32, tag = "10")]
    pub degree: u32,
    #[prost(uint32, tag = "11")]
    pub indegree: u32,
    #[prost(uint32, tag = "12")]
    pub outdegree: u32,
    #[prost(float, tag = "13")]
    pub pagerank: f32,
    #[prost(float, tag = "14")]
    pub betweenness: f32,
    #[prost(uint32, tag = "15")]
    pub kcore: u32,
    #[prost(uint32, tag = "16")]
    pub community: u32,
    #[prost(uint32, tag = "17")]
    pub wcc: u32,
    /// Full markdown body of the note (frontmatter stripped). Lazily read
    /// from disk on each `/node/:id` request — we don't pre-load every
    /// body into memory because a 10k-node vault would balloon the
    /// server's RSS. Empty for external nodes (no corresponding file) or
    /// when the read fails. Frontmatter is *not* duplicated here; it
    /// lives in `frontmatter_json` (field 7).
    #[prost(string, tag = "18")]
    pub body: ::prost::alloc::string::String,
}
/// Search response. Returned by /search?q=…
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResults {
    #[prost(string, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "2")]
    pub total: u32,
}
/// Per-field inverted index. Returned by /graph/meta_summary.
/// `fields\[i\]` names a field; each `FieldBucket.field_idx` indexes into it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaSummary {
    #[prost(string, repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub buckets: ::prost::alloc::vec::Vec<FieldBucket>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldBucket {
    #[prost(uint32, tag = "1")]
    pub field_idx: u32,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "3")]
    pub node_idx: ::prost::alloc::vec::Vec<u32>,
}
