//! graph-compute — standalone gRPC graph-layout solver.
//!
//! Today this ships:
//!   - the tonic gRPC service (`Compute::Subscribe` + `Compute::Health` +
//!     `Compute::TopoFisheye`)
//!   - a single shared simulation state advanced by a tokio task
//!   - a `tokio::sync::broadcast` fan-out so multiple subscribers see the same frames
//!   - a registry of selectable layout engines ([`engines`]), driven by the sim
//!     loop via the [`engines::LayoutEngine`] trait (ADR-001). The brute-force
//!     wgpu/WGSL ForceAtlas2 sim is the first engine (`"fa2-brute"`); a
//!     CPU spring integrator (`"cpu-spring"`) is the GPU-less fallback.
//!
//! The remaining roadmap — Barnes-Hut, SGD-stress, maxent, a multilevel wrapper,
//! and a CSR-partition + ghost-node halo-exchange model for horizontal scaling —
//! is documented in `docs/compute-architecture.md`, and the algorithm research
//! behind it in `docs/layout-algorithms.md`. The legacy standalone [`WgpuSim`]
//! is retained for reference but no longer drives the loop; the FA2 engine
//! (`engines::Fa2BruteEngine`) is the port that does.
//!
//! (Historical note: an earlier scaffold targeted CUDA + NCCL; the project
//! standardized on wgpu/WGSL so the same kernels run natively and in the
//! browser. The distributed model is now framed around wgpu workers, not NCCL.)

pub mod proto {
    // Generated by tonic-build from proto/compute.proto.
    tonic::include_proto!("graph_compute");
}

pub mod bsp;
pub mod engines;
pub mod partition;
pub mod sim;
pub mod service;
pub mod topo_fisheye;
pub mod wgpu_sim;

pub use engines::{
    CpuSpringEngine, CsrShard, EngineCtx, EngineRegistry, Fa2BruteEngine, GeometricEngine,
    GpuCtx, GraphAttributes, HaloUpdate, LayoutEngine, ShardMeta, StepOutput,
};
pub use partition::{
    partition_csr, run_superstep, run_superstep_local, HaloDelta, HaloTransport, LocalTransport,
    Partition, TonicHaloTransport, Worker,
};
pub use bsp::{run_bsp_mesh, BspWorker, LiveHaloProvider, MeshTransport};
pub use service::HaloProvider;
pub use wgpu_sim::WgpuSim;
