//! graph-compute — CUDA force-simulation worker (Phase 1 scaffold).
//!
//! Phase 1 ships:
//!   - the tonic gRPC service (`Compute::Subscribe` + `Compute::Health`)
//!   - a single shared simulation state advanced by a tokio task
//!   - a `tokio::sync::broadcast` fan-out so multiple subscribers see the same frames
//!   - a CUDA path gated behind the `cuda` feature; the kernel itself is a stub
//!
//! Phase 2 fills in NCCL halo exchange, multi-GPU partitioning, and a real
//! port of `crates/graph-layouts`'s wgsl force kernel into CUDA C compiled via nvrtc.

pub mod proto {
    // Generated by tonic-build from proto/compute.proto.
    tonic::include_proto!("graph_compute");
}

pub mod sim;
pub mod service;
