{{- if and .Values.graphCompute.enabled .Values.graphCompute.session.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jump-cannon.fullname" . }}-gpu-session-template
  labels:
    {{- include "jump-cannon.labels" . | nindent 4 }}
    app.kubernetes.io/component: graph-api
data:
  raycluster.yaml: |
    {{- include "jump-cannon.rayclusterManifest" . | nindent 4 }}
{{- end }}
