{{- if .Values.graphCompute.enabled }}
{{- $computeNamespace := include "jump-cannon.computeNamespace" . }}
{{- if not .Values.graphCompute.session.enabled }}
{{ include "jump-cannon.rayclusterManifest" . }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jump-cannon.computeName" . }}
  namespace: {{ $computeNamespace }}
  labels:
    {{- include "jump-cannon.labels" . | nindent 4 }}
    app.kubernetes.io/component: graph-compute
spec:
  type: ClusterIP
  selector:
    ray.io/cluster: {{ include "jump-cannon.computeName" . }}
    ray.io/node-type: head
  ports:
    - name: grpc
      port: {{ .Values.graphCompute.service.port }}
      targetPort: grpc
      protocol: TCP
{{- end }}
