//! prost-generated protobuf types for the graph-api wire format.
//!
//! Generated by `build.rs` from `crates/graph-api/proto/graph.proto`.
//! The package is `jumpcannon.graph`.

include!(concat!(env!("OUT_DIR"), "/jumpcannon.graph.rs"));
