//! Protobuf message types for graph-api's wire format.
//!
//! The schema lives in `crates/graph-api/proto/graph.proto`; the prost output
//! is checked in (rather than generated by a build.rs) so this workspace is
//! self-contained — no protoc, no reach outside `app/` — which keeps the
//! crane/nix build pure. After changing graph.proto, run `just app-proto`
//! to regenerate. Drift is low-risk in the meantime: protobuf ignores unknown
//! fields and defaults missing ones.

#![allow(dead_code)] // MetaSummary/FieldBucket aren't consumed by a panel yet

include!("proto/jumpcannon.graph.rs");
